[package]
name = "mdbook-ruby"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
mdbook = "0.4.4"
serde_json = "1.0.59"
toml = "0.5.7"
regex = "0.1"